<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\nodekey\Entity\NodeKeyEntity;

function _nodekey_check_content_type($node) {
    $content_types = \Drupal::config('nodekey.settings')->get('content_types');
    if ($content_types) {
        foreach ($content_types as $key => $bundle) {
            if ($bundle === 0) {
                continue;
            }
            if ($bundle == $node->getType()) {
                return true;
            }
        }
    }
    return false;
}

function nodekey_node_presave($node) {
    if (_nodekey_check_content_type($node)) {
        $nodekey = $node->get('nodekey')->value;
        $existing = NodeKeyEntity::count($nodekey);
        if ($existing == 0) {
            $nodekey = NodeKeyEntity::create($node);
            $node->set('nodekey', $nodekey);
            drupal_set_message(sprintf(t('The node key « %s » has been created.', array(), array('context' => 'nodekey')), $nodekey));
        } elseif ($existing > 1) {
            drupal_set_message(sprintf(t('The node key « %s » already exists. Please fix it in your database.', array(), array('context' => 'nodekey')), $nodekey), 'warning');
        }
    }
}