<?php
use Drupal\nodekey\Entity\NodeKeyEntity;

function _nodekey_check_content_type($node) {
    $content_types = \Drupal::config('nodekey.settings')->get('content_types');
    if ($content_types) {
        foreach ($content_types as $key => $bundle) {
            if ($bundle === 0) {
                continue;
            }
            if ($bundle == $node->getType()) {
                return true;
            }
        }
    }
    return false;
}

function nodekey_node_presave($node) {
    if (_nodekey_check_content_type($node)) {
        $nodekey = $node->get('nodekey')->value;
        $existing = NodeKeyEntity::count($nodekey);
        if ($existing == 0) {
            $nodekey = NodeKeyEntity::create($node);
            $node->set('nodekey', $nodekey);			
			\Drupal::messenger()->addMessage(sprintf(t('The node key « %s » has been created.', array(), array('context' => 'nodekey')), $nodekey));
        } elseif ($existing > 1) {
			\Drupal::messenger()->addMessage(sprintf(t('The node key « %s » already exists. Please fix it in your database.', array(), array('context' => 'nodekey')), $nodekey), 'warning');
        }
    }
}

function nodekey_theme_suggestions_page_alter(array &$suggestions)
{
	if ($node = \Drupal::routeMatch()->getParameter('node')) {
		if ($node->hasField('nodekey')) {
			$nodekey = $node->get('nodekey')->value;
			$suggestions[] = 'page__' . $nodekey;
		}
	}
}

function nodekey_theme_suggestions_node_alter(array &$suggestions)
{
	if ($node = \Drupal::routeMatch()->getParameter('node')) {
		if ($node->hasField('nodekey')) {
			$nodekey = $node->get('nodekey')->value;
			$suggestions[] = 'node__' . $nodekey;
		}
	}
}